### PR TITLE
Add register definitions for ATmega8

### PR DESCRIPTION
**Pull request by cmnrd**

### CODE REVIEW

**Comment by cmnrd** [comment]
Please spell 'twbr' in last line with capital letters.

**Comment by cmnrd** [comment]
The code is syntactical incorrect as the sublime snippet has a bug (see #14). @elli89 Please fix the register definitions.

**Comment by el-han** [comment]
Register set is complete now. Please merge the atmega8 branch into master.

**Comment by cmnrd** [comment]
Closed by 606759bfca763d732c1aa7fc767c6725e87246a0

**Pull request closed without merging**
