### PR TITLE
premake fix to use pkg-config to find simavr location

### PR DESCRIPTION
**Pull request by stfngrt**
Use pkg-config to automatically find simavr include files

### CODE REVIEW

**Comment by stfngrt** [comment]
this does not work and should not be merged

**Comment by cmnrd** [comment]
I checked it. It is not working because on my system pkg-config adds the path /usr/include/simavr where the static path before was set to /usr/include/simavr/avr. It is not a problem with premake or pkg-config but a problem with our includes. We have to inlcude avr/avr_mcu_section.h instead of avr_mcu_section.h

**Comment by stfngrt** [comment]
Ok this seems to solve the problem. I will change the required files.

**Comment by stfngrt** [comment]
This should be merged into staging.

**Comment by cmnrd** [comment]
Thanks! Merged into master

**Pull request closed without merging**
